
services:
  mariadb:
    container_name: mariadb
    env_file: .env
    networks:
      - inception_net
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${SQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  nginx:
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    depends_on:
      - wordpress
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started  
    restart: on-failure
    expose:
     - "9000"

  redis:
    container_name: redis
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    restart: on-failure

  ftp:
    container_name: ftp
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    ports:
      - "20-21:20-21/tcp"
      - "21000-21010:21000-21010/tcp"
    restart: on-failure
    
  portfolio:
    container_name: portfolio
    env_file: .env
    networks:
      - inception_net
    build: ./requirements/bonus/portfolio
    expose:
    - "8081"
    restart: on-failure

  adminer:
    container_name: adminer
    env_file: .env
    networks:
      - inception_net
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    expose:
      - "8080"
    restart: on-failure

  portainer:
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    env_file: .env
    networks:
      - inception_net
    depends_on:
      - mariadb
    build: ./requirements/bonus/portainer
    ports:
      - "9001:9000"
      - "9443:9443"
      - "8000:8000"
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jnauroy/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jnauroy/data/mariadb'

  portainer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jnauroy/data/portainer'

networks:
  inception_net:
    driver: bridge
